FROM nginx
RUN rm -rf /usr/share/nginx/html/index.html
RUN echo "<h1>Hi i'm from APP-1" > /usr/share/nginx/html/index.html

#create a docker image and push image to docker hub and then write a manifest file